package wasm-components:dom@0.1.0;

interface types {
    variant prop-value {
        int(s32),
        str(string),
        boolean(bool),
        float(f64),
    }

    variant opcode {
        open(string),
        close,
        attr(tuple<string, string>),
        text(string),
        slot(string),
        event(tuple<string, string>),
        child(string),
        prop(tuple<string, prop-value>),
        attr-slot(tuple<string, string>),
        begin(string),
        end,
    }
}

interface renderer {
    use types.{opcode, prop-value};
    render: func(props: list<tuple<string, prop-value>>) -> list<opcode>;
    handle-event: func(handler: string);
}

interface host {
    event-query: func(path: string) -> string;
}

world leaf-component {
    import host;
    export renderer;
}

world pure-component {
    export renderer;
}
